### ISSUE TITLE
fuse: panic in handler for Read

### ISSUE THREAD

**Issue by piratsch** [itsToggle/rclone_RD#32]
#### What is the problem you are having with rclone?

I consistently get the following error messages:
```
Feb 26 21:10:16 [hostname] rclone-linux[3741]: fuse: panic in handler for Read [ID=0xc Node=0x1 Uid=1000 Gid=1000 Pid=3757] 0x1 4096 @0x0 dir=true fl=0 owner=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock: runtime error: invalid memory address or nil pointer dereference
Feb 26 21:10:16 [hostname] rclone-linux[3741]: goroutine 38 [running]:
Feb 26 21:10:16 [hostname] rclone-linux[3741]: bazil.org/fuse/fs.(*Server).serve.func2()
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:994 +0x14e
Feb 26 21:10:16 [hostname] rclone-linux[3741]: panic({0x18b6ca0, 0x2d49920})
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Program Files/Go/src/runtime/panic.go:838 +0x207
Feb 26 21:10:16 [hostname] rclone-linux[3741]: github.com/rclone/rclone/backend/realdebrid.(*Fs).listAll(0xc00089df40, {0x2020c68?, 0xc000050098}, {0x1bc2e1f, 0x1}, 0x0, 0x0, 0xc0006376d0)
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/backend/realdebrid/realdebrid.go:530 +0x3d43
Feb 26 21:10:16 [hostname] rclone-linux[3741]: github.com/rclone/rclone/backend/realdebrid.(*Fs).List(0xc00089df40, {0x2020c68, 0xc000050098}, {0x0, 0x0})
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/backend/realdebrid/realdebrid.go:828 +0x125
Feb 26 21:10:16 [hostname] rclone-linux[3741]: github.com/rclone/rclone/fs/list.DirSorted({0x2020c68, 0xc000050098}, {0x2030ea8?, 0xc00089df40?}, 0x0, {0x0, 0x0})
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/fs/list/list.go:24 +0x83
Feb 26 21:10:16 [hostname] rclone-linux[3741]: github.com/rclone/rclone/vfs.(*Dir)._readDir(0xc00004f080)
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:453 +0x11b
Feb 26 21:10:16 [hostname] rclone-linux[3741]: github.com/rclone/rclone/vfs.(*Dir).ReadDirAll(0xc00004f080)
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:814 +0x54
Feb 26 21:10:16 [hostname] rclone-linux[3741]: github.com/rclone/rclone/cmd/mount.(*Dir).ReadDirAll(0xc0001ac090, {0x1bb40e0?, 0xc0001ac090?})
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/cmd/mount/dir.go:108 +0x14a
Feb 26 21:10:16 [hostname] rclone-linux[3741]: bazil.org/fuse/fs.(*Server).handleRequest(0xc0003707e0, {0x2020c30, 0xc00005c440}, {0x200fc60?, 0xc0001ac090}, 0xc00005c040, {0x201b3d0?, 0xc00033e070?}, 0xc000637f08)
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1378 +0xb57
Feb 26 21:10:16 [hostname] rclone-linux[3741]: bazil.org/fuse/fs.(*Server).serve(0xc0003707e0, {0x201b3d0, 0xc00033e070})
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1015 +0x634
Feb 26 21:10:16 [hostname] rclone-linux[3741]: bazil.org/fuse/fs.(*Server).Serve.func1()
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:512 +0x69
Feb 26 21:10:16 [hostname] rclone-linux[3741]: created by bazil.org/fuse/fs.(*Server).Serve
Feb 26 21:10:16 [hostname] rclone-linux[3741]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:510 +0x3be
```

`ls` in the mounted directory results in `ls: reading directory '.': Input/output error` and files cannot be accessed

#### What is your rclone version (output from `rclone version`)
https://github.com/itsToggle/rclone_RD/releases/tag/v1.58.1-rd.2.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 20.01 64 bit

Currently not really usable for me.

**Comment by itsToggle** [comment]
Yeah that crash is the same as the ones reported in #28. realdebrid is not returning a status code, which is a case that i did not handle in two locations.

**Comment by arsaboo** [comment]
@itsToggle I am seeing the same error, was this fixed? I am using the latest builds you linked

**Comment by arsaboo** [comment]
Here are the logs:
```bash
$ ./rclone-linux_non_beta  mount debrid_rd: /data/debrid --dir-cache-time 10s --vfs-cache-mode full --allow-other --allow-non-empty
2023/03/22 20:57:20 fuse: panic in handler for Lookup [ID=0x6 Node=0x1 Uid=1000 Gid=1000 Pid=3237] ".Trash": runtime error: invalid memory address or nil pointer dereference
goroutine 56 [running]:
bazil.org/fuse/fs.(*Server).serve.func2()
        C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:994 +0x14e
panic({0x18b6ca0, 0x2d49920})
        C:/Program Files/Go/src/runtime/panic.go:838 +0x207
github.com/rclone/rclone/backend/realdebrid.(*Fs).listAll(0xc00076e820, {0x2020c68?, 0xc0001a8008}, {0x1bc2e1f, 0x1}, 0x0, 0x0, 0xc0006e56b0)
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/backend/realdebrid/realdebrid.go:530 +0x3d43
github.com/rclone/rclone/backend/realdebrid.(*Fs).List(0xc00076e820, {0x2020c68, 0xc0001a8008}, {0x0, 0x0})
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/backend/realdebrid/realdebrid.go:828 +0x125
github.com/rclone/rclone/fs/list.DirSorted({0x2020c68, 0xc0001a8008}, {0x2030ea8?, 0xc00076e820?}, 0x0, {0x0, 0x0})
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/fs/list/list.go:24 +0x83
github.com/rclone/rclone/vfs.(*Dir)._readDir(0xc00030c300)
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:453 +0x11b
github.com/rclone/rclone/vfs.(*Dir).stat(0xc00030c300, {0xc00053917a, 0x6})
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:702 +0xbb
github.com/rclone/rclone/vfs.(*Dir).Stat(0x1bb40e0?, {0xc00053917a?, 0x1bcac20?})
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:799 +0x27
github.com/rclone/rclone/cmd/mount.(*Dir).Lookup(0xc00021db80, {0x200fc60?, 0xc00021db80?}, 0xc0001bb540, 0xc0001e6000)
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/cmd/mount/dir.go:77 +0x188
bazil.org/fuse/fs.(*Server).handleRequest(0xc00054e000, {0x2020c30, 0xc000494040}, {0x200fc60?, 0xc00021db80}, 0xc0001bb400, {0x201b280?, 0xc0001bb540?}, 0xc0006e5f08)
        C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1187 +0x27fe
bazil.org/fuse/fs.(*Server).serve(0xc00054e000, {0x201b280, 0xc0001bb540})
        C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1015 +0x634
bazil.org/fuse/fs.(*Server).Serve.func1()
        C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:512 +0x69
created by bazil.org/fuse/fs.(*Server).Serve
        C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:510 +0x3be
2023/03/22 20:57:20 fuse: panic in handler for Lookup [ID=0x8 Node=0x1 Uid=1000 Gid=1000 Pid=3237] ".Trash-1000": runtime error: invalid memory address or nil pointer dereference
goroutine 47 [running]:
bazil.org/fuse/fs.(*Server).serve.func2()
        C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:994 +0x14e
panic({0x18b6ca0, 0x2d49920})
        C:/Program Files/Go/src/runtime/panic.go:838 +0x207
github.com/rclone/rclone/backend/realdebrid.(*Fs).listAll(0xc00076e820, {0x2020c68?, 0xc0001a8008}, {0x1bc2e1f, 0x1}, 0x0, 0x0, 0xc0006e16b0)
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/backend/realdebrid/realdebrid.go:530 +0x3d43
github.com/rclone/rclone/backend/realdebrid.(*Fs).List(0xc00076e820, {0x2020c68, 0xc0001a8008}, {0x0, 0x0})
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/backend/realdebrid/realdebrid.go:828 +0x125
github.com/rclone/rclone/fs/list.DirSorted({0x2020c68, 0xc0001a8008}, {0x2030ea8?, 0xc00076e820?}, 0x0, {0x0, 0x0})
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/fs/list/list.go:24 +0x83
github.com/rclone/rclone/vfs.(*Dir)._readDir(0xc00030c300)
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:453 +0x11b
github.com/rclone/rclone/vfs.(*Dir).stat(0xc00030c300, {0xc000664a20, 0xb})
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:702 +0xbb
github.com/rclone/rclone/vfs.(*Dir).Stat(0x1bb40e0?, {0xc000664a20?, 0x1bcac20?})
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:799 +0x27
github.com/rclone/rclone/cmd/mount.(*Dir).Lookup(0xc00021db80, {0x200fc60?, 0xc00021db80?}, 0xc00098ac00, 0xc0001e60c0)
        C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/cmd/mount/dir.go:77 +0x188
bazil.org/fuse/fs.(*Server).handleRequest(0xc00054e000, {0x2020c30, 0xc0001ba180}, {0x200fc60?, 0xc00021db80}, 0xc0001bb400, {0x201b280?, 0xc00098ac00?}, 0xc0006e1f08)
        C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1187 +0x27fe
bazil.org/fuse/fs.(*Server).serve(0xc00054e000, {0x201b280, 0xc00098ac00})
        C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1015 +0x634
bazil.org/fuse/fs.(*Server).Serve.func1()
        C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:512 +0x69
created by bazil.org/fuse/fs.(*Server).Serve
```

**Comment by piratsch** [comment]
Thanks a lot for fixing this! :heart: 

My server used to crash once a day at least, and now it has been running without major issues for 4 days!
